"""Shared machinery for the coding-agent CLI executors (claude / codex / grok).

Each concrete executor differs only in its argv shape, capabilities, and how the prompt is
delivered (arg vs stdin). Everything else — tier→model resolution, the invoke skeleton,
doctrine → workspace-file rendering, the version/auth doctor probe — is identical and lives
here. Shell is deliberately NOT built on this (no model, no config, its own invoke).
"""

from __future__ import annotations

import os
import shutil
import tempfile
from pathlib import Path

from cairn.executors.base import (
    ExecTimeout,
    Finding,
    Invocation,
    Result,
    parse_step_sentinel,
    run_process,
)
from cairn.kernel.config import ExecutorConfig
from cairn.kernel.errors import ConfigError


def _render_doctrine(doctrine: Path) -> str:
    """Doctrine content under a one-line generated header (kept dumb + deterministic)."""
    header = f"<!-- Generated by cairn from {doctrine.name}. Do not edit; edit the doctrine. -->"
    return f"{header}\n\n{doctrine.read_text(encoding='utf-8')}"


def _probe_version(name: str, timeout_s: float = 15.0) -> tuple[int | None, str]:
    """Run ``<name> --version`` for doctor. Uses the ambient env (a machine preflight, not an
    agent invocation) so PATH/HOME are available. Returns (exit_code|None-on-timeout, output)."""
    with tempfile.TemporaryDirectory() as td:
        try:
            code, out, _ = run_process(
                [name, "--version"],
                stdin_text=None,
                env=os.environ.copy(),
                cwd=Path.cwd(),
                timeout_s=timeout_s,
                log_path=Path(td) / "version.log",
            )
        except ExecTimeout:
            return None, ""
        return code, out.strip()


class CliExecutor:
    """Base for the three CLI-backed executors. Subclasses set ``name``/``capabilities``,
    ``_workspace_file`` (or None), and implement ``_build_command``."""

    name: str = ""
    _workspace_file: str | None = None  # CLAUDE.md / AGENTS.md / None
    _install_hint: str = ""

    def __init__(self, config: ExecutorConfig) -> None:
        self.config = config

    # -- model resolution --------------------------------------------------- #

    def resolve_model(self, tier: str, effort: str) -> tuple[str, str | None]:
        try:
            spec = self.config.tiers[tier]
        except KeyError:
            raise ConfigError(
                f"executor {self.name!r} has no tier {tier!r} "
                f"(configured: {', '.join(sorted(self.config.tiers)) or 'none'})"
            ) from None
        # A tier may fix effort (alias-style); otherwise the agent's effort flows through.
        effort_out = spec.effort if spec.effort is not None else effort
        return (spec.model, effort_out)

    # -- invocation --------------------------------------------------------- #

    def invoke(self, inv: Invocation) -> Result:
        prompt_text = inv.prompt_file.read_text(encoding="utf-8")
        argv, stdin_text = self._build_command(inv, prompt_text)
        exit_code, output, duration_s = run_process(
            argv,
            stdin_text=stdin_text,
            env=inv.env,
            cwd=inv.cwd,
            timeout_s=inv.timeout_s,
            log_path=inv.log_path,
            redactor=inv.redactor,
        )
        return Result(
            step=parse_step_sentinel(output),
            exit_code=exit_code,
            duration_s=duration_s,
        )

    def _build_command(self, inv: Invocation, prompt_text: str) -> tuple[list[str], str | None]:
        """Return (argv, stdin_text). The ONE place argv is shaped — re-verify against the
        CLI's ``--help`` at doctor time; vendors drift."""
        raise NotImplementedError

    # -- workspace + guards ------------------------------------------------- #

    def render_workspace(self, ws) -> None:
        if self._workspace_file is None:
            return
        doctrine = getattr(ws, "doctrine", None)
        if doctrine is None:
            return
        target = Path(ws.root) / self._workspace_file
        content = _render_doctrine(Path(doctrine))
        if target.exists() and target.read_text(encoding="utf-8") == content:
            return  # idempotent: only write when missing or changed
        target.write_text(content, encoding="utf-8")

    def install_guards(self, guards, ws, run_dir) -> None:
        return None  # base no-op; ClaudeExecutor overrides to install the PreToolUse hook

    # -- doctor ------------------------------------------------------------- #

    def doctor(self) -> list[Finding]:
        if shutil.which(self.name) is None:
            return [Finding("error", f"executor {self.name!r} not found", fix=self._install_hint)]
        code, out = _probe_version(self.name)
        if code is None:
            return [Finding("error", f"{self.name} --version timed out", fix=self._install_hint)]
        if code != 0:
            return [
                Finding("error", f"{self.name} --version failed (exit {code})", fix=self._install_hint)
            ]
        findings: list[Finding] = []
        pin = self.config.pin_version
        if pin and pin not in out:
            findings.append(
                Finding(
                    "warning",
                    f"{self.name} reports {out!r}, workspace pins {pin!r}",
                    fix=f"install {self.name}@{pin}",
                )
            )
        return findings
